# Generated by Django 4.2.16 on 2026-06-21 11:55

import apps.resumes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=apps.resumes.models.resume_upload_path)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.PositiveIntegerField(help_text='Bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('error', 'Error')], default='pending', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('raw_text', models.TextField(blank=True)),
                ('contact_info', models.JSONField(default=dict)),
                ('skills', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('total_years_experience', models.FloatField(blank=True, null=True)),
                ('seniority_level', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
