# Generated by Django 4.2.16 on 2026-06-21 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ats_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('match_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('keyword_match_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('experience_match_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skills_match_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_required_skills', models.JSONField(default=list)),
                ('missing_preferred_skills', models.JSONField(default=list)),
                ('matched_keywords', models.JSONField(default=list)),
                ('missing_keywords', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('gaps', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('resume_improvements', models.JSONField(default=list)),
                ('overall_verdict', models.CharField(blank=True, max_length=255)),
                ('hire_probability', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='jobs.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_results',
                'ordering': ['-created_at'],
                'unique_together': {('resume', 'job_description')},
            },
        ),
    ]
